#pragma once

#include "stdafx.h"

#define ADJUST_CRECT_ARRAY_LEN	8

#define SCREEN_CAPTURE_STATE_NONE		0
#define SCREEN_CAPTURE_STATE_START		1
#define SCREEN_CAPTURE_STATE_RESIZE		2

#define RESIZE_LOCATION_NONE		0
#define RESIZE_LOCATION_NORTHWEST	1
#define RESIZE_LOCATION_SOUTHEAST	2
#define RESIZE_LOCATION_NORTHEAST	3
#define RESIZE_LOCATION_SOUTHWEST	4
#define RESIZE_LOCATION_NORTH		5
#define RESIZE_LOCATION_SOUTH		6
#define RESIZE_LOCATION_WEST		7
#define RESIZE_LOCATION_EAST		8
#define RESIZE_LOCATION_AREA		9

#define SELECT_AREA_EDIT_NONE			0
#define SELECT_AREA_EDIT_DRAW_RECT		1
#define SELECT_AREA_EDIT_DRAW_CIRCLE	2
#define SELECT_AREA_EDIT_DRAW_ARROW		3
#define SELECT_AREA_EDIT_DRAW_TEXT		4

#define FONT_ADJUST						8
#define DEFAULT_FONT					_T("Î¢ÈíÑÅºÚ")